force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <label>Invoice Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Final_Settlement_Payment_Received__c.field-meta.xml
<CustomField>
    <fullName>Final_Settlement_Payment_Received__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Final Settlement Payment Received</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Resource__c.field-meta.xml
<CustomField>
    <fullName>Resource__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Resource</label>
    <referenceTo>Resource__c</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Resource__c/Resource__c.object-meta.xml
<CustomObject>
    <label>Resource</label>
    <nameField>
        <label>Developer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Resources</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Timesheet_Entry__c/Timesheet_Entry__c.object-meta.xml
<CustomObject>
    <label>Timesheet Entry</label>
    <nameField>
        <label>Timesheet Entry Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Timesheet Entries</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Timesheet_Entry__c/fields/Actual_Days_worked__c.field-meta.xml
<CustomField>
    <fullName>Actual_Days_worked__c</fullName>
    <formula>ROUND(Captured_Hours__c / 8, 0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Actual Days worked</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Timesheet_Entry__c/fields/Approved__c.field-meta.xml
<CustomField>
    <fullName>Approved__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Marks whether the timesheet has been approved.</description>
    <label>Approved</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Timesheet_Entry__c/fields/Approved_Days__c.field-meta.xml
<CustomField>
    <fullName>Approved_Days__c</fullName>
    <label>Approved Days</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Timesheet_Entry__c/fields/Billable__c.field-meta.xml
<CustomField>
    <fullName>Billable__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates whether the work is billable.</description>
    <label>Billable</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Timesheet_Entry__c/fields/Captured_Hours__c.field-meta.xml
<CustomField>
    <fullName>Captured_Hours__c</fullName>
    <label>Captured Hours</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Timesheet_Entry__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <description>The ending date of the timesheet period.</description>
    <label>End Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Timesheet_Entry__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Associates the timesheet entry with the specific project.</description>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Timesheet Entries</relationshipLabel>
    <relationshipName>Timesheet_Entries</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Timesheet_Entry__c/fields/Resource__c.field-meta.xml
<CustomField>
    <fullName>Resource__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Links the timesheet entry to the developer (resource) record.</description>
    <label>Resource</label>
    <referenceTo>Resource__c</referenceTo>
    <relationshipLabel>Timesheet Entries</relationshipLabel>
    <relationshipName>Timesheet_Entries</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Timesheet_Entry__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>The starting date of the timesheet period.</description>
    <label>Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Timesheet_Entry__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>The current status of the timesheet entry.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Deactive</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Validated</fullName>
            </value>
            <value>
                <fullName>Active,</fullName>
                <isActive>false</isActive>
                <label>Active,</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Timesheet_Entry__c/fields/Submitted_On__c.field-meta.xml
<CustomField>
    <fullName>Submitted_On__c</fullName>
    <description>Date and time when the timesheet was submitted.</description>
    <label>Submitted On</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Timesheet_Entry__c/fields/Worked_Days__c.field-meta.xml
<CustomField>
    <fullName>Worked_Days__c</fullName>
    <description>Total number of days the developer was scheduled to work during the timesheet period.</description>
    <label>Worked Days</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/TimesheetViewerController.cls
/**
* @File Name : TimesheetViewerController.cls
* @Description :
* @Author :
* @Last Modified By :
* @Last Modified On : April 7, 2025
* @Modification Log :
*==============================================================================
* Ver | Date | Author | Modification
*==============================================================================
* 1.0 | April 7, 2025 |   | Initial Version
**/

public class TimesheetViewerController {
	@AuraEnabled
    public static List<Timesheet_Entry__c> getTimesheets() {
        return [
            SELECT Id, Resource__r.Name, Project__r.Name, Start_Date__c, End_Date__c, Project__r.Final_Settlement_Payment_Received__c,
                   Worked_Days__c, Actual_Days_worked__c, Billable__c, Approved__c,
                   Submitted_On__c, Status__c, Captured_Hours__c, Approved_Days__c
            FROM Timesheet_Entry__c WHERE Project__r.Status__c IN ('In Progress' , 'On Hold')
            ORDER BY Submitted_On__c DESC
        ];
    }

    @AuraEnabled
    public static void updateWorkedDays(List<Timesheet_Entry__c> timesheets) {
    update timesheets;
    }

    //For  creat Invoice
    @AuraEnabled
public static Id createInvoice(Id timesheetId) {
    try {
        List<Invoice__c> invoicesToUpdate = new List<Invoice__c>();

        // Get all field API names for Timesheet_Entry__c
        Map<String, Schema.SObjectField> tsFieldsMap = Schema.getGlobalDescribe().get('Timesheet_Entry__c').getDescribe().fields.getMap();
        List<String> tsFieldNames = new List<String>(tsFieldsMap.keySet());
        
        
        // Build dynamic SOQL to fetch all fields for the timesheet
        String soql = 'SELECT ' + String.join(tsFieldNames, ',') + ', Project__r.Name FROM Timesheet_Entry__c WHERE Id = :timesheetId ORDER BY CreatedDate DESC LIMIT 1';
        System.debug('SOQL == :' + soql);
        Timesheet_Entry__c ts = Database.query(soql);

        // Find existing invoice for this project
        List<Invoice__c> existInvoices = [SELECT Id FROM Invoice__c WHERE Project__c = :ts.Project__c LIMIT 1];

        Invoice__c inv;
        Boolean isUpdate = false;

        // Initialize the invoice record
        if (!existInvoices.isEmpty()) {
            inv = existInvoices[0];
            isUpdate = true;
        } else {
            inv = new Invoice__c();
            inv.Project__c = ts.Project__c;
            inv.Name = 'Invoice for - ' + ts.Project__r.Name;
            inv.Invoice_Number__c = 'INV-' + String.valueOf(Datetime.now().getTime());
            inv.Quantity__c = ts.Captured_Hours__c;
        }

        // Get Invoice fields
        Map<String, Schema.SObjectField> invoiceFields = Schema.getGlobalDescribe().get('Invoice__c').getDescribe().fields.getMap();

        // Dynamic field mapping
        for (String invoiceField : invoiceFields.keySet()) {
            if (tsFieldsMap.containsKey(invoiceField)) {
                Schema.DescribeFieldResult fieldDescribe = invoiceFields.get(invoiceField).getDescribe();
                if (fieldDescribe.isUpdateable() && !fieldDescribe.isCalculated()) {
                    try {
                        inv.put(invoiceField, ts.get(invoiceField));
                    } catch (Exception ex) {
                        System.debug('Skipping field due to error: ' + invoiceField + ' -> ' + ex.getMessage());
                    }
                }
            }
        }

        // Static/default fields (set or override as needed)
        inv.Invoice_Number__c = 'INV-' + String.valueOf(Datetime.now().getTime());
        inv.Quantity__c = ts.Captured_Hours__c;

        invoicesToUpdate.add(inv);

        // Save the record
        if (isUpdate) {
            Database.SaveResult[] srList = Database.update(invoicesToUpdate, false);
            for (Database.SaveResult sr : srList) {
                if (!sr.isSuccess()) {
                    System.debug('Update failed: ' + sr.getErrors()[0].getMessage());
                }
            }
        } else {
            Database.SaveResult[] srList = Database.insert(invoicesToUpdate, false);
            for (Database.SaveResult sr : srList) {
                if (!sr.isSuccess()) {
                    System.debug('Insert failed: ' + sr.getErrors()[0].getMessage());
                }
            }
        }

        return inv.Id;

    } catch (Exception ex) {
        System.debug('Error in createInvoice: ' + ex.getMessage());
        throw new AuraHandledException('Failed to create or update invoice: ' + ex.getMessage());
    }
}

    
    // METHOD  — Get Timesheets with Incomplete Payment Projects
    @AuraEnabled(cacheable=true)
    public static List<Timesheet_Entry__c> getTimesheetsForIncompletePayment() {
        return [SELECT Id, Resource__r.Name, Project__c, Project__r.Name, Project__r.Final_Settlement_Payment_Received__c, 
                       Start_Date__c, End_Date__c, Worked_Days__c, Actual_Days_worked__c, 
                       Billable__c, Approved__c, Submitted_On__c, Status__c, Captured_Hours__c, Approved_Days__c
                FROM Timesheet_Entry__c
                WHERE Project__r.Final_Settlement_Payment_Received__c = False ORDER BY Submitted_On__c DESC];
    }

    //  METHOD  — Get All Timesheet Entries WITH Project Payment Status
    // @AuraEnabled(cacheable=true)
    // public static List<Timesheet_Entry__c> getTimesheetsForIncompletePayment(Boolean toggleValue) {
        
    //     if(isToggleOn){
    //         return [SELECT Id, Resource__r.Name, Project__c, Project__r.Name, Project__r.Final_Settlement_Payment_Received__c, 
    //                    Start_Date__c, End_Date__c, Worked_Days__c, Actual_Days_worked__c, 
    //                    Billable__c, Approved__c, Submitted_On__c, Status__c, Captured_Hours__c, Approved_Days__c
    //                    FROM Timesheet_Entry__c
    //                    WHERE Project__r.Final_Settlement_Payment_Received__c = False ORDER BY Submitted_On__c DESC];  
            
    //     }
    //     else{
    //         return [SELECT Id, Resource__r.Name, Project__c, Project__r.Name, Project__r.Final_Settlement_Payment_Received__c,
    //                     Start_Date__c, End_Date__c, Worked_Days__c, Actual_Days_worked__c, 
    //                     Billable__c, Approved__c, Submitted_On__c, Status__c, Captured_Hours__c, Approved_Days__c
    //                     FROM Timesheet_Entry__c WHERE Status__c IN ('In Progress' , 'On Hold')
    //                     ORDER BY Submitted_On__c DESC];
    //     }
            
    // }
}