force-app/main/default/objects/Resource__c/Resource__c.object-meta.xml
<CustomObject>
    <label>Resource</label>
    <nameField>
        <label>Developer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Resources</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Resource__c/fields/Efficiency__c.field-meta.xml
<CustomField>
    <fullName>Efficiency__c</fullName>
    <formula>IF(Experience__c &gt;= 1,
    Totel_Project_Assigned__c / 2,
    NULL
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Efficiency</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Resource__c/fields/Experience__c.field-meta.xml
<CustomField>
    <fullName>Experience__c</fullName>
    <label>Experience</label>
    <precision>4</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/teamEfficiencyTrackingController.cls
/**
* @File Name : teamEfficiencyTrackingController.cls
* @Description :
* @Author :
* @Last Modified By :
* @Last Modified On : April 14, 2025
* @Modification Log :
*==============================================================================
* Ver | Date | Author | Modification
*==============================================================================
* 1.0 | April 14, 2025 |   | Initial Version
**/

public  with sharing class teamEfficiencyTrackingController {
	
	@AuraEnabled(cacheable=true)
	public static List<Resource__c> getResourceEfficiencyData(){
		return [ Select Id, Name, Efficiency__c From Resource__c Where Experience__c != NUll];
	}
	
}