unpackaged/objects/Keyword_Config__mdt.object
<CustomObject>
    <fields>
        <fullName>Keyword__c</fullName>
        <label>Keyword</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Routing_Queue_Name__c</fullName>
        <label>Routing_Queue_Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Keyword Config</label>
    <pluralLabel>Keyword Configs</pluralLabel>
</CustomObject>

unpackaged/objects/Product__c.object
<CustomObject>
    <fields>
        <fullName>Brand__c</fullName>
        <description>Specifies the brand to which the product belongs</description>
        <label>Brand</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Baby Cakes</fullName>
                </value>
                <value>
                    <fullName>Black &amp; Decker</fullName>
                </value>
                <value>
                    <fullName>Breadman</fullName>
                </value>
                <value>
                    <fullName>Cooks</fullName>
                </value>
                <value>
                    <fullName>Copper Chef</fullName>
                </value>
                <value>
                    <fullName>Emeril Lagasse</fullName>
                </value>
                <value>
                    <fullName>Farberware</fullName>
                </value>
                <value>
                    <fullName>George Foreman</fullName>
                </value>
                <value>
                    <fullName>Juiceman</fullName>
                </value>
                <value>
                    <fullName>LUMABELLA</fullName>
                </value>
                <value>
                    <fullName>Luma Bella</fullName>
                </value>
                <value>
                    <fullName>Maxim</fullName>
                </value>
                <value>
                    <fullName>Melitta</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>PowerXL</fullName>
                </value>
                <value>
                    <fullName>REMINGTON</fullName>
                </value>
                <value>
                    <fullName>Russell Hobbs</fullName>
                </value>
                <value>
                    <fullName>Toastmaster</fullName>
                </value>
                <value>
                    <fullName>Westinghouse</fullName>
                </value>
                <value>
                    <fullName>Windmere</fullName>
                </value>
                <value>
                    <fullName>Power (Tristar)</fullName>
                    <isActive>false</isActive>
                    <label>Power (Tristar)</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Model_Number__c</fullName>
        <description>Product&apos;s unique model identifier</description>
        <label>Model Number</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Line__c</fullName>
        <description>Specifies the exact product type or line</description>
        <label>Product Line</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>AFTO</fullName>
                </value>
                <value>
                    <fullName>Air Fry Ovens</fullName>
                </value>
                <value>
                    <fullName>Air-Styler</fullName>
                </value>
                <value>
                    <fullName>Bikini Trimmer</fullName>
                </value>
                <value>
                    <fullName>Blenders</fullName>
                </value>
                <value>
                    <fullName>Body Groomer</fullName>
                </value>
                <value>
                    <fullName>Bread Makers</fullName>
                </value>
                <value>
                    <fullName>Brushes</fullName>
                </value>
                <value>
                    <fullName>Can Openers</fullName>
                </value>
                <value>
                    <fullName>Classic Irons</fullName>
                </value>
                <value>
                    <fullName>Coffee Grinders</fullName>
                </value>
                <value>
                    <fullName>Coffee Makers</fullName>
                </value>
                <value>
                    <fullName>Container Cooking - Other</fullName>
                </value>
                <value>
                    <fullName>Crepe Makers</fullName>
                </value>
                <value>
                    <fullName>Curling Iron</fullName>
                </value>
                <value>
                    <fullName>Deep Fryers</fullName>
                </value>
                <value>
                    <fullName>Detail Trimmer</fullName>
                </value>
                <value>
                    <fullName>Digital Steam Irons</fullName>
                </value>
                <value>
                    <fullName>Dryer</fullName>
                </value>
                <value>
                    <fullName>Dual Foil</fullName>
                </value>
                <value>
                    <fullName>Electric Knives</fullName>
                </value>
                <value>
                    <fullName>Epilator</fullName>
                </value>
                <value>
                    <fullName>Facial Brush</fullName>
                </value>
                <value>
                    <fullName>Fan Heater</fullName>
                </value>
                <value>
                    <fullName>Foil</fullName>
                </value>
                <value>
                    <fullName>Food Processors</fullName>
                </value>
                <value>
                    <fullName>Food Steamers</fullName>
                </value>
                <value>
                    <fullName>Griddles/Skillets</fullName>
                </value>
                <value>
                    <fullName>Grills - Charcoal</fullName>
                </value>
                <value>
                    <fullName>Grills - Fixed Plate</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Product Detail</label>
    <nameField>
        <displayFormat>PD-{00000}</displayFormat>
        <label>Product Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/classes/CaseFormHelper.cls
public without sharing class CaseFormHelper {

    public static Id getProductId(String brand, String productLine, String model) {
        List<Product__c> products = [
            SELECT Id FROM Product__c 
            WHERE Brand__c LIKE :brand 
              AND Product_Line__c LIKE :productLine 
              AND Model_Number__c LIKE :model 
            LIMIT 1
        ];
        return products.isEmpty() ? null : products[0].Id;
    }

    public static Id getKeywordRelatedQueue(String emailContent, String supportAddress) {
        List<Keyword_Config__mdt> configList = CaseUtility.getKeywordConfigMdtBySupportEmail(supportAddress);
        if (!configList.isEmpty() && 
            CaseUtility.isValidKeywordFound(configList[0].Keyword__c.split(',\\s*'), emailContent)) {

            Group queue = [SELECT Id FROM Group 
                           WHERE Name = :configList[0].Routing_Queue_Name__c 
                           AND Type = 'Queue' 
                           LIMIT 1];

            return queue.Id;
        }
        return null;
    }

    public static Case constructCaseRecord(Map<String, String> params) {
        Case c = new Case();
        try {
            System.debug('params:- ' + params);
            c.SuppliedName            = params.get('name');
            c.SuppliedEmail           = params.get('email');
            c.SuppliedPhone           = params.get('phone');
            c.Subject                 = params.get('subject');
            c.Description             = params.get('description');
            c.Custom_Reason_for_Contact__c = params.get('Reason_for_Contact__c');
            c.Form_Submitted_Date__c  = System.now();
            c.Product__c              = getProductId(params.get('Brand__c'), params.get('Raw_Product_Line__c'), params.get('Raw_Model_Number__c'));
        } catch (Exception e) {
            System.debug('exception occured in constructCaseRecord:- ' + e.getMessage());
        }
        return c;
    }

    public static void insertAttachments(Id caseId, Map<String, String> params) {
        List<ContentVersion> contentVersions = new List<ContentVersion>();
        Integer index = 0;

        while (true) {
            String nameKey = 'fileName' + index;
            String contentKey = 'fileContent' + index;

            if (!params.containsKey(nameKey) || !params.containsKey(contentKey)) break;

            String fileName = params.get(nameKey);
            String fileContent = params.get(contentKey);

            if (String.isNotBlank(fileName) && String.isNotBlank(fileContent)) {
                contentVersions.add(new ContentVersion(
                    Title = fileName,
                    PathOnClient = '/' + fileName,
                    VersionData = EncodingUtil.base64Decode(fileContent)
                ));
            }
            index++;
        }

        if (contentVersions.isEmpty()) return;

        List<Id> insertedIds = new List<Id>();
        for (Database.SaveResult res : Database.insert(contentVersions, false)) {
            if (res.isSuccess()) insertedIds.add(res.getId());
        }

        if (insertedIds.isEmpty()) return;

        List<ContentDocumentLink> links = new List<ContentDocumentLink>();
        for (ContentVersion cv : [
            SELECT Id, ContentDocumentId 
            FROM ContentVersion 
            WHERE Id IN :insertedIds AND ContentDocumentId != null
        ]) {
            links.add(new ContentDocumentLink(
                LinkedEntityId = caseId,
                ContentDocumentId = cv.ContentDocumentId,
                ShareType = 'V',
                Visibility = 'AllUsers'
            ));
        }

        if (!links.isEmpty()) insert links;
    }

    public static Map<String, List<String>> getModelMap(String brandName) {
        Map<String, List<String>> modelMap = new Map<String, List<String>>();

        for (Product__c pm : 
            [SELECT Brand__c, Model_Number__c, Product_Line__c 
             FROM Product__c 
             WHERE Brand__c = :brandName]) {

            if (!modelMap.containsKey(pm.Product_Line__c)) {
                modelMap.put(pm.Product_Line__c, new List<String>());
            }
            modelMap.get(pm.Product_Line__c).add(pm.Model_Number__c);
        }
        return modelMap;
    }

    public static List<String> getReasonForContactOptions() {
        /*List<String> options = new List<String>();
        Schema.DescribeFieldResult fieldResult = Case.Custom_Reason_for_Contact__c.getDescribe();

        for (Schema.PicklistEntry entry : fieldResult.getPicklistValues()) {
            options.add(entry.getValue());
        }*/
        
        String resonForContact = System.Label.ReasonForContactForCustomer;
        List<String> options = resonForContact.split(',');
        
        return options;
    }

    public static List<String> getBrandOptions() {
        List<String> options = new List<String>();
        Schema.DescribeFieldResult fieldResult = Product__c.Brand__c.getDescribe();

        for (Schema.PicklistEntry entry : fieldResult.getPicklistValues()) {
            options.add(entry.getValue()); 
        }
        return options;
    }

}