unpackaged/objects/Knowledge__kav.object
<CustomObject>
    <articleTypeChannelDisplay>
        <articleTypeTemplates>
            <channel>App</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Prm</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Csp</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Pkb</channel>
            <template>Toc</template>
        </articleTypeTemplates>
    </articleTypeChannelDisplay>
    <fields>
        <fullName>Brand__c</fullName>
        <description>Shows which brands the article is related to.</description>
        <label>Brand</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Baby Cakes</fullName>
                </value>
                <value>
                    <fullName>Black &amp; Decker</fullName>
                </value>
                <value>
                    <fullName>Breadman</fullName>
                </value>
                <value>
                    <fullName>Cooks</fullName>
                </value>
                <value>
                    <fullName>Copper Chef</fullName>
                </value>
                <value>
                    <fullName>Emeril Lagasse</fullName>
                </value>
                <value>
                    <fullName>Farberware</fullName>
                </value>
                <value>
                    <fullName>George Foreman</fullName>
                </value>
                <value>
                    <fullName>Juiceman</fullName>
                </value>
                <value>
                    <fullName>LUMABELLA</fullName>
                </value>
                <value>
                    <fullName>Luma Bella</fullName>
                </value>
                <value>
                    <fullName>Maxim</fullName>
                </value>
                <value>
                    <fullName>Melitta</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Power (Tristar)</fullName>
                </value>
                <value>
                    <fullName>PowerXL</fullName>
                </value>
                <value>
                    <fullName>REMINGTON</fullName>
                </value>
                <value>
                    <fullName>Russell Hobbs</fullName>
                </value>
                <value>
                    <fullName>Toastmaster</fullName>
                </value>
                <value>
                    <fullName>Westinghouse</fullName>
                </value>
                <value>
                    <fullName>Windmere</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product_Category__c</fullName>
        <description>Categorizes the article based on the related product type.</description>
        <label>Product Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Accessories</fullName>
                </value>
                <value>
                    <fullName>Beauty and Wellness</fullName>
                </value>
                <value>
                    <fullName>Beverage</fullName>
                </value>
                <value>
                    <fullName>Cooking</fullName>
                </value>
                <value>
                    <fullName>Female Grooming</fullName>
                </value>
                <value>
                    <fullName>Female Shave</fullName>
                </value>
                <value>
                    <fullName>Food Preparation</fullName>
                </value>
                <value>
                    <fullName>Garment</fullName>
                </value>
                <value>
                    <fullName>Grills</fullName>
                </value>
                <value>
                    <fullName>Haircare</fullName>
                </value>
                <value>
                    <fullName>Male Grooming</fullName>
                </value>
                <value>
                    <fullName>Male Shave</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Spare Parts</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product_Line__c</fullName>
        <description>Product Name</description>
        <label>Product Line</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>ABCoaster</fullName>
                </value>
                <value>
                    <fullName>AbToner</fullName>
                </value>
                <value>
                    <fullName>AirClimber</fullName>
                </value>
                <value>
                    <fullName>AirFryer</fullName>
                </value>
                <value>
                    <fullName>AirFryer360</fullName>
                </value>
                <value>
                    <fullName>AirFryerGrill</fullName>
                </value>
                <value>
                    <fullName>AirFryerGrillCombo</fullName>
                </value>
                <value>
                    <fullName>AirFryerOven6q</fullName>
                </value>
                <value>
                    <fullName>AirFryerOven8q</fullName>
                </value>
                <value>
                    <fullName>AirFryerOvenProUnk</fullName>
                </value>
                <value>
                    <fullName>AirFryerOvenUnk</fullName>
                </value>
                <value>
                    <fullName>AirFryerPro</fullName>
                </value>
                <value>
                    <fullName>AirFryerTurbo</fullName>
                </value>
                <value>
                    <fullName>AirFryerVortex</fullName>
                </value>
                <value>
                    <fullName>AirPurifier</fullName>
                </value>
                <value>
                    <fullName>AquaRug</fullName>
                </value>
                <value>
                    <fullName>BestKitchenHacks</fullName>
                </value>
                <value>
                    <fullName>BluBreeze</fullName>
                </value>
                <value>
                    <fullName>Calista</fullName>
                </value>
                <value>
                    <fullName>ClearDash</fullName>
                </value>
                <value>
                    <fullName>Contour</fullName>
                </value>
                <value>
                    <fullName>CopperChef</fullName>
                </value>
                <value>
                    <fullName>CopperWear</fullName>
                </value>
                <value>
                    <fullName>CouponFrenchFry</fullName>
                </value>
                <value>
                    <fullName>CouponGrocery</fullName>
                </value>
                <value>
                    <fullName>ElectricSkillet</fullName>
                </value>
                <value>
                    <fullName>FlexHose</fullName>
                </value>
                <value>
                    <fullName>FreeClearTV</fullName>
                </value>
                <value>
                    <fullName>FusionExcelerator</fullName>
                </value>
                <value>
                    <fullName>GenieProducts</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Knowledge</label>
    <pluralLabel>Knowledge</pluralLabel>
</CustomObject>

unpackaged/objects/Product__c.object
<CustomObject>
    <fields>
        <fullName>Brand__c</fullName>
        <description>Specifies the brand to which the product belongs</description>
        <label>Brand</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Baby Cakes</fullName>
                </value>
                <value>
                    <fullName>Black &amp; Decker</fullName>
                </value>
                <value>
                    <fullName>Breadman</fullName>
                </value>
                <value>
                    <fullName>Cooks</fullName>
                </value>
                <value>
                    <fullName>Copper Chef</fullName>
                </value>
                <value>
                    <fullName>Emeril Lagasse</fullName>
                </value>
                <value>
                    <fullName>Farberware</fullName>
                </value>
                <value>
                    <fullName>George Foreman</fullName>
                </value>
                <value>
                    <fullName>Juiceman</fullName>
                </value>
                <value>
                    <fullName>LUMABELLA</fullName>
                </value>
                <value>
                    <fullName>Luma Bella</fullName>
                </value>
                <value>
                    <fullName>Maxim</fullName>
                </value>
                <value>
                    <fullName>Melitta</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>PowerXL</fullName>
                </value>
                <value>
                    <fullName>REMINGTON</fullName>
                </value>
                <value>
                    <fullName>Russell Hobbs</fullName>
                </value>
                <value>
                    <fullName>Toastmaster</fullName>
                </value>
                <value>
                    <fullName>Westinghouse</fullName>
                </value>
                <value>
                    <fullName>Windmere</fullName>
                </value>
                <value>
                    <fullName>Power (Tristar)</fullName>
                    <isActive>false</isActive>
                    <label>Power (Tristar)</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product_Line__c</fullName>
        <description>Specifies the exact product type or line</description>
        <label>Product Line</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>AFTO</fullName>
                </value>
                <value>
                    <fullName>Air Fry Ovens</fullName>
                </value>
                <value>
                    <fullName>Air-Styler</fullName>
                </value>
                <value>
                    <fullName>Bikini Trimmer</fullName>
                </value>
                <value>
                    <fullName>Blenders</fullName>
                </value>
                <value>
                    <fullName>Body Groomer</fullName>
                </value>
                <value>
                    <fullName>Bread Makers</fullName>
                </value>
                <value>
                    <fullName>Brushes</fullName>
                </value>
                <value>
                    <fullName>Can Openers</fullName>
                </value>
                <value>
                    <fullName>Classic Irons</fullName>
                </value>
                <value>
                    <fullName>Coffee Grinders</fullName>
                </value>
                <value>
                    <fullName>Coffee Makers</fullName>
                </value>
                <value>
                    <fullName>Container Cooking - Other</fullName>
                </value>
                <value>
                    <fullName>Crepe Makers</fullName>
                </value>
                <value>
                    <fullName>Curling Iron</fullName>
                </value>
                <value>
                    <fullName>Deep Fryers</fullName>
                </value>
                <value>
                    <fullName>Detail Trimmer</fullName>
                </value>
                <value>
                    <fullName>Digital Steam Irons</fullName>
                </value>
                <value>
                    <fullName>Dryer</fullName>
                </value>
                <value>
                    <fullName>Dual Foil</fullName>
                </value>
                <value>
                    <fullName>Electric Knives</fullName>
                </value>
                <value>
                    <fullName>Epilator</fullName>
                </value>
                <value>
                    <fullName>Facial Brush</fullName>
                </value>
                <value>
                    <fullName>Fan Heater</fullName>
                </value>
                <value>
                    <fullName>Foil</fullName>
                </value>
                <value>
                    <fullName>Food Processors</fullName>
                </value>
                <value>
                    <fullName>Food Steamers</fullName>
                </value>
                <value>
                    <fullName>Griddles/Skillets</fullName>
                </value>
                <value>
                    <fullName>Grills - Charcoal</fullName>
                </value>
                <value>
                    <fullName>Grills - Fixed Plate</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Product Detail</label>
    <nameField>
        <displayFormat>PD-{00000}</displayFormat>
        <label>Product Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/classes/Knowledge.cls
public class Knowledge {
    @AuraEnabled(cacheable=true)
    public static KnowledgeResultWrapper getKnowledgeRecords(String recordId) {
        String Brand, Category, ProductLine, reason, description , status;
        case caseRecord = [Select Id,Status, Brand__c, custom_reason_for_contact__c, Description, Product__c, Product__r.Product_Line__c, Product__r.Product_Category__c, Product__r.Brand__c FROM Case WHERE Id = : recordId LIMIT 1];

        if (caseRecord != null) {
            if (caseRecord.Product__r != null) {
                ProductLine = caseRecord.Product__r.Product_Line__c;
                Category = caseRecord.Product__r.Product_Category__c;
                Brand = caseRecord.Product__r.Brand__c;
            } else {
                Brand = caseRecord.Brand__c;
            }
            reason = caseRecord.custom_reason_for_contact__c;
            description = caseRecord.Description;
            status = caseRecord.Status;
        } else {
        }

        String baseQuery = 'SELECT Question__c, Answer__c, Title, Product_Name__c, Product_Category__c, Brand__c, KnowledgeArticleId FROM knowledge__kav';
        List<String> conditions = new List<String>();

        if (String.isNotBlank(ProductLine)) {
            conditions.add('Product_Name__c = :ProductLine');
        }
        if (String.isNotBlank(Brand)) {
            conditions.add('Brand__c = :Brand');
        }
        String fullQuery = baseQuery;

        if (!conditions.isEmpty()) {
            String whereClause = String.join(conditions, ' AND ');
            fullQuery += ' WHERE ' + whereClause;
        }
        List<knowledge__kav> records = Database.query(fullQuery);
        return new KnowledgeResultWrapper(reason, description,status, records);
    }

    @AuraEnabled(cacheable=true)
    public static List<knowledge__kav> getGlobalKnowledgeRecords(String searchKeyword) {
        String escapedKeyword = String.escapeSingleQuotes(searchKeyword);
        List<List<SObject>> searchResults = Search.query(
            'FIND :escapedKeyword IN ALL FIELDS RETURNING Knowledge__kav(Id, KnowledgeArticleId, Question__c, Answer__c WHERE PublishStatus = \'Online\' AND Language = \'en_US\')'
        );
        List<Knowledge__kav> articles = (List<Knowledge__kav>) searchResults[0];
        return articles;
    }



    public class KnowledgeResultWrapper {
        @AuraEnabled public String reasonForContact;
        @AuraEnabled public String description;
        @AuraEnabled public String status;
        @AuraEnabled public List<knowledge__kav> knowledgeRecords;

        public KnowledgeResultWrapper(String reason, String description,String status, List<knowledge__kav> records) {
            this.reasonForContact = reason;
            this.description = description;
            this.knowledgeRecords = records;
            this.status = status;
        }
    }

    @AuraEnabled
    public static Boolean displayKnowledge(Id caseId, Id userId) {
        return [
            SELECT Id
            FROM AgentWork
            WHERE WorkItemId = :caseId
            AND UserId = :userId
            AND Status = 'Opened'
            LIMIT 1
        ].size() > 0;
    }

    @AuraEnabled
    public static List<Vote> getVoteCount(String recordId) {
        return [SELECT Id, ParentId, Parent.Type, CreatedDate, CreatedBy.Name, CreatedById, type FROM Vote where ParentId = :recordId];
    }

    @AuraEnabled
    public static void voteForknoledgeArticle(String parentId, String voteType, String userId) {
        if(String.isNotBlank(parentId) && String.isNotBlank(userId)){
            List<Vote> existingVote = [SELECT Id, ParentId, Parent.Type, CreatedDate, CreatedBy.Name, CreatedById, type FROM Vote where ParentId = :parentId AND CreatedBy.Id = :userId LIMIT 1];
            if(!existingVote.isEmpty() && String.isNotBlank(voteType)){
                existingVote[0].type = voteType;
                update existingVote[0];
            } else if(!existingVote.isEmpty() && !String.isNotBlank(voteType)) {
                delete existingVote[0];
            } else {
                Vote objVote = new Vote();
                objVote.ParentId = parentId;
                objVote.type = voteType;
                if(!test.isRunningTest())
                {
                    insert objVote;
                }
                else{
                }
                
            }
        }
    }
}