unpackaged/objects/Product__c.object
<CustomObject>
    <fields>
        <fullName>Brand__c</fullName>
        <description>Specifies the brand to which the product belongs</description>
        <label>Brand</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Baby Cakes</fullName>
                </value>
                <value>
                    <fullName>Black &amp; Decker</fullName>
                </value>
                <value>
                    <fullName>Breadman</fullName>
                </value>
                <value>
                    <fullName>Cooks</fullName>
                </value>
                <value>
                    <fullName>Copper Chef</fullName>
                </value>
                <value>
                    <fullName>Emeril Lagasse</fullName>
                </value>
                <value>
                    <fullName>Farberware</fullName>
                </value>
                <value>
                    <fullName>George Foreman</fullName>
                </value>
                <value>
                    <fullName>Juiceman</fullName>
                </value>
                <value>
                    <fullName>LUMABELLA</fullName>
                </value>
                <value>
                    <fullName>Luma Bella</fullName>
                </value>
                <value>
                    <fullName>Maxim</fullName>
                </value>
                <value>
                    <fullName>Melitta</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>PowerXL</fullName>
                </value>
                <value>
                    <fullName>REMINGTON</fullName>
                </value>
                <value>
                    <fullName>Russell Hobbs</fullName>
                </value>
                <value>
                    <fullName>Toastmaster</fullName>
                </value>
                <value>
                    <fullName>Westinghouse</fullName>
                </value>
                <value>
                    <fullName>Windmere</fullName>
                </value>
                <value>
                    <fullName>Power (Tristar)</fullName>
                    <isActive>false</isActive>
                    <label>Power (Tristar)</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Product Detail</label>
    <nameField>
        <displayFormat>PD-{00000}</displayFormat>
        <label>Product Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/classes/CaseFollowUpFormControllerTest.cls
@isTest
private class CaseFollowUpFormControllerTest {

    @testSetup
    static void setupTestData() {
        Case testCase = new Case(
            Subject = 'Test Case',
            SuppliedName = 'Jane Doe',
            SuppliedEmail = 'janedoe@example.com',
            Status = 'Open'
        );
        insert testCase;
    }

    @isTest
    static void testMissingTicketParam() {
        Test.startTest();
        ApexPages.currentPage().getParameters().clear();
        new CaseFollowUpFormController();
        Test.stopTest();
    }

    @isTest
    static void testInvalidBase64Ticket() {
        Test.startTest();
        ApexPages.currentPage().getParameters().put('ticket', 'invalidbase64==');
        new CaseFollowUpFormController();
        Test.stopTest();
    }

    @isTest
    static void testValidTicketInitialization() {
        Case c = [SELECT Id, CaseNumber FROM Case LIMIT 1];
        String encodedTicket = EncodingUtil.base64Encode(Blob.valueOf(c.CaseNumber));
        Test.startTest();
        ApexPages.currentPage().getParameters().put('ticket', encodedTicket);
        new CaseFollowUpFormController();
        Test.stopTest();
    }

    @isTest
    static void testSubmitForm() {
        Case c = [SELECT Id, CaseNumber FROM Case LIMIT 1];
        String encodedTicket = EncodingUtil.base64Encode(Blob.valueOf(c.CaseNumber));

        ApexPages.currentPage().getParameters().put('ticket', encodedTicket);
        ApexPages.currentPage().getParameters().put('Subject', 'New Subject');
        ApexPages.currentPage().getParameters().put('Description', 'Updated description');
        ApexPages.currentPage().getParameters().put('Product__c', 'Some Product');
        ApexPages.currentPage().getParameters().put('Brand__c', 'Sample Brand');
        ApexPages.currentPage().getParameters().put('Model__c', 'Sample Model');

        Test.startTest();
        CaseFollowUpFormController controller = new CaseFollowUpFormController();
        controller.submitForm();
        Test.stopTest();
    }

    @isTest
    static void testRemoteActions() {
        Test.startTest();
        CaseFollowUpFormController.getBrandOptions();
        CaseFollowUpFormController.getReasonForContactOptions();
        CaseFollowUpFormController.getModelMap('TestBrand');
        Test.stopTest();
    }
}